/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-auto-decimal
type ToDecimal = import('unplugin-auto-decimal/types').ToDecimal
declare interface String {
  toDecimal: ToDecimal
}
declare interface Number {
  toDecimal: ToDecimal
}
